### ISSUE TITLE
mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to net.minecraftforge.fluids.IFluidHandler

### ISSUE THREAD

**Issue by lightning02** [CovertJaguar/Railcraft#811] opened 2016-04-28 08:28 UTC
http://pastebin.com/zJ0Mt2ii
Hi guys, 
The entire server suddenly crashed and it happened for apparently no reason, I was flyng around with a chisel block in the hand and some other stuff, maybe it was caused by some low pressure boiler tank chunk-loaded somewhere in dimension 0 (overworld).
I was in a RFtool dimension when the crash occurred and I was building some salination tower (mekanism) that may explain the "mekanism" part in the crash log but there was no fluid present at the moment.. it was all dry, that's the real strange thing...

In your opinion I have to post it also at Mekanism owner?

**Comment by CovertJaguar** [comment] 2016-04-30 18:10
Sometimes the game gets TileEntities mixed up, you must always do an instanceof check before casting TileEntities. This is nothing I can fix from my end.

**Comment by CovertJaguar** [comment] 2016-04-30 18:10
Duplicate of #451

**Closed** 2016-04-30 18:11 UTC
Labels: can't fix, duplicate, not railcraft

**Comment by lightning02** [comment] 2016-05-01 20:20
an istanceof check before cast TileEntities"? what do you mean exactly?how do I do that?
sorry for my ignorance °-°

**Comment by Forecaster** [comment] 2016-05-01 21:19
You don't. You report this to Mekanism.
