### ISSUE TITLE
RC Multiblocks unforming

### ISSUE THREAD

**Issue by JasonMcRay** [CovertJaguar/Railcraft#730] opened 2015-11-17 15:18 UTC
One player of my modpack Infitech 2 has reported his multiblock structions (Tank, Turbine) getting unformed after he returns back from nether. To fix that he needs to go back to nether and back. Tested with RC9.7.0.0 but also with latest 9.8.0.0.

**Comment by liach** [comment] 2015-11-17 15:56
Copying this:
```
java.lang.RuntimeException: Tile entity mods.railcraft.common.plugins.ic2.TileIC2MultiEmitterDelegate@abcde6d must return at least 1 sub tile for IMetaDelegate.getSubTiles().
    at ic2.core.energy.Tile.<init>(Tile.java:28) ~[Tile.class:?]
    at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:101) ~[EnergyNetLocal.class:?]
    at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66) ~[EnergyNetLocal.class:?]
    at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28) ~[EventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_186_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
    at mods.railcraft.common.plugins.ic2.IC2Plugin.addTileToNet(IC2Plugin.java:71) [IC2Plugin.class:?]
    at mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine.addToNet(TileSteamTurbine.java:253) [TileSteamTurbine.class:?]
    at mods.railcraft.common.blocks.machine.alpha.TileSteamTurbine.func_145845_h(TileSteamTurbine.java:181) [TileSteamTurbine.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

**Comment by CovertJaguar** [comment] 2016-03-24 23:55
Duplicate of #711

**Closed by CovertJaguar** 2016-03-24 23:55 UTC
Labels: duplicate
