### ISSUE TITLE
Railcraft related crash ?

### ISSUE THREAD

**Issue by Carbon-Ghost** [CovertJaguar/Railcraft#604] opened 2015-05-09 20:20 UTC
Using latest railcraft version, I get this : http://paste.ee/p/olFMS, any ideas on what is causing this ? 

It seems related with fluids, and MAYBE mfr or mekanism, but I am not 100% sure, that's just a guess.

**Comment by liach** [comment] 2015-05-09 23:30
CovertJaguar has said that you might need to disable steam block if you are using forge 10.13.2.x. That's all. The fluid conflict with MineFactoryReloaded.

**Comment by CovertJaguar** [comment] 2015-05-10 07:59
Duplicate of #592

**Closed by CovertJaguar** 2015-05-10 07:59 UTC
