### ISSUE TITLE
[Suggestion] Make Cart Inventories TFC Compatible

### ISSUE THREAD

**Issue by abculatter2** [CovertJaguar/Railcraft#835] opened 2016-05-31 09:56 UTC
TerraFirmaCraft has a container tick handler, which must be called in order for its food to decay and heated items to cool down. I was wondering if it might be possible to have RC's cart inventories call this method if TFC is installed?

EDIT: Apparently, this is more difficult then I anticipated it would be, due to incompatibilities on TFC's side. Probably not going to happen, but I can DREAM!

**Comment by AEnterprise** [comment] 2016-05-31 14:44
TFC can probably do this from their end by using capabilities, attaching one on each TE with an inventory and using that for the food decay (atleast for TE's where the items are accessable)

**Comment by Forecaster** [comment] 2016-06-08 08:28
@AEnterprise They already do this. The issue is that decay doesn't happen in railcraft minecarts.

**Comment by AEnterprise** [comment] 2016-06-08 11:08
@Forecaster yes but forge allows you to attach capabilities onto TE's that are not your own

**Comment by Forecaster** [comment] 2016-06-08 12:01
And this works on entities such as minecarts?

**Comment by AEnterprise** [comment] 2016-06-08 12:03
it should http://mcforge.readthedocs.io/en/latest/datastorage/capabilities/#attaching-capabilities

**Comment by XFactHD** [comment] 2016-06-08 16:34
What about vanilla hopper minecarts, does it work with those when Railcraft is not installed?

**Comment by AEnterprise** [comment] 2016-06-08 17:22
if they use this method it should as all carts are entities

**Comment by williewillus** [comment] 2016-06-08 19:56
Well caps doesn't matter because those don't exist in 1.7

**Comment by AEnterprise** [comment] 2016-06-09 07:05
for 1.7 but there is barely development for 1.7.10 atm so as doubt we will see new version of RC or TFC on 1.7.10 but TFC can implement this on 1.8+

**Comment by Forecaster** [comment] 2016-06-09 07:59
At this point the ball has left our court entirely it seems. Should probably close this issue and interested parties can bring it up at TFC instead.

**Comment by CovertJaguar** [comment] 2016-06-09 08:13
I should also point out that you can hook into the MinecartUpdate event as well.

**Comment by AEnterprise** [comment] 2016-06-09 08:37
yeah, it can be done from RC's end but it would be much, much better if TFC does it from it's end as that would be cleaner, less likely to cause issues and compatible with other mods that add carts

**Closed** 2016-06-09 19:16 UTC
Labels: enhancement, not railcraft, priority-low
