### ISSUE TITLE
Metal Platforms not Dropping

### ISSUE THREAD

**Issue by slawr34** [CovertJaguar/Railcraft#387] opened 2014-11-16 07:18 UTC
I am having a bug where metal platforms (grey metal platforms) don't drop when broken with a pickaxe. Not sure if this is intentional. 

Edit - 
Neither are grey metal posts.

**Comment by liach** [comment] 2017-03-03 20:38
@slawr34 Does this still happen with latest verions for 1.7?

**Comment by liach** [comment] 2017-03-14 00:14
Some Ticon picks dig platforms even slower than an empty hand for some reason. For those picks which break platforms and posts in a reasonable time (i.e. faster than bare hand) they drop platforms.

**Comment by CovertJaguar** [comment] 2017-03-14 00:17
I redid all the harvest types for RC 10, maybe it fixed it.

**Comment by liach** [comment] 2017-03-14 00:18
@CovertJaguar My test result is that this is working as intended. So I will close this issue.

**Closed by liach** 2017-03-14 00:18 UTC
Labels: not a bug, working as intended
