### ISSUE TITLE
Issue with Railcraft tanks

### ISSUE THREAD

**Issue by mostwanted12354** [CovertJaguar/Railcraft#711] opened 2015-10-13 18:48 UTC
1.7.10 version 9.7.0.0 My steel tanks are not rendering as a multiblock structure upon login and i have to break a block and replace it to render correctly, If a picture of mod list or a screen shot of the tanks are needed please let me know.

Thank you =)

**Comment by CovertJaguar** [comment] 2015-10-14 15:56
This is usually caused by Cauldron.

**Comment by mostwanted12354** [comment] 2015-10-14 18:33
i do not have Cauldron installed. These are the Mods I have installed. Here is my mods list: http://pastebin.com/sA7wne3a   

It is an updated version of Bevo's Tech Pack

**Comment by ranger135xp** [comment] 2015-10-17 00:14
Can confirm, Cauldron is not installed

**Comment by reteo** [comment] 2015-11-14 03:24
I'm encountering this issue as well, but Ender IO is not installed on my modpack.

**Comment by CovertJaguar** [comment] 2016-03-24 23:31
Possibly fixed by 1fa265ff0d14dab2b71f0fae47417831da4361a7

**Closed by CovertJaguar** 2016-03-24 23:31 UTC
Labels: bug, needs verification
