### ISSUE TITLE
Ticking block entity/World Anchor problem.

### ISSUE THREAD

**Issue by killerscorpion** [CovertJaguar/Railcraft#759] opened 2016-01-01 23:41 UTC
Forge build 10.13.4.1566
Railcraft 9.8.0.0

Apologies if this has already been dealt with.

I get this crash like every other time I load my world: http://pastebin.com/bBPWJs2C. I have a world anchor in the nether with a config setting to not require fuel to run. I removed the anchor and replaced it, but this crash still occurs. Its not a constant crash, when this happens I just restart the client and my world loads fine, but then later if I try to load it again this crash happens.

**Comment by liach** [comment] 2016-01-01 23:44
Duplicate of #653. Fixed in next release.

**Comment by killerscorpion** [comment] 2016-01-01 23:46
Awesome, glad to know its fixed!

**Comment by liach** [comment] 2016-01-01 23:47
Oh my bad it should be #753. Close it please.

**Closed** 2016-01-02 03:13 UTC
