### ISSUE TITLE
Minecart dupe bug and infinitely placeable vanilla carts.

### ISSUE THREAD

**Issue by 1337phreak** [CovertJaguar/Railcraft#614] opened 2015-05-20 21:33 UTC
I've run into a problem with placing any of the vanilla minecarts in my modpack.  I am able to infintlely place them as it doesn't use up the one in my hand also if I bump into the one that was placed it splits into two, waila shows both named entity.MinecartRidable.name one says Railcraft and the other says Minecraft beneath them.  I haven't noticed the bugs with any of the non-vanilla railcraft carts.

My modpack uses smbarbour's MCUpdater and the pack can be found here: 

http://miningcore.net/game-minecraft.php

Server:  kcauldron-1.7.10-4.1403.65-server.jar (also tried with cauldron-1.7.10-2.1403.1.54)

Mods: 
AgriCraft-1.7.10-1.3.1
AOBD-2.6.2
AppleCore-mc1.7.10-1.0.2
BetterFoliage-1.0.3
BetterTitleScreen-1.7.10-1.1
buildcraft-7.0.4
buildcraft-compat-7.0.2
CarpentersBlocks
CodeChickenCore-1.7.10-1.0.6.44-universal
CoFHCore-[1.7.10]3.0.2-262
CoroUtil-1.1.1
CraftGuide-1.6.8.1
CustomOreGen-1.7.10-1.2.18
DynamicLights-1.7.10
Enhanced Biomes 2.5 for MC 1.7.10
EnviroMine-1.3.117
Farseek-1.0.7
HQM-The Journey (4.2.4)
HungerOverhaul-1.7.10-beta.5
IguanaTweaks-1.7.10-Beta-19
Minetweaker3-1.7.10-3.0.9C
MobiusCore-1.2.5_1.7.10
ModTweaker 2-0.8.1
NotEnoughItems-1.7.10-1.0.4.107-universal
Opis-1.2.5_1.7.10
Pam's HarvestCraft 1.7.10f
PFAA-1.7.10-0.2.23
PlayerAPI-1.7.10-1.2
ProjectRed-1.7.10-1.2
ProjectRed-1.7.10-4.6.1.80-Base
ProjectRed-1.7.10-4.6.1.80-Compat
ProjectRed-1.7.10-4.6.1.80-Integration
ProjectRed-1.7.10-4.6.1.80-Lighting
ProjectRed-1.7.10-4.6.1.80-World
Railcraft_1.7.10-9.6.0.0  (also tried with 9.6.1.0)
Revamp-1.3.1
SmartCore-1.7.10-1.0
SmartMoving-1.7.10-15.3
SmartRender-1.7.10-2.1
SoundFilters-0.8_for_1.7.X
SpiceOfLife-mc1.7.10-1.2.3
Streams-0.1.4
ThermalExpansion-[1.7.10]4.0.1-182
ThermalFoundation-[1.7.10]1.0.0-81
UpdateCheckerMod-1.7.10
Waila-1.5.8a_1.7.10
Weather-2.3.7

**Comment by liach** [comment] 2015-05-21 01:07
Reproducable with clean kcauldron, right?

**Comment by 1337phreak** [comment] 2015-05-21 01:15
The kcauldron I'm using is from here: http://sourceforge.net/projects/cauldron-unofficial/files/

Yes, I've removed all of the other mods from the pack except Railcraft_1.7.10-9.6.0.0.jar and the carts are still duping.

**Comment by CovertJaguar** [comment] 2015-05-21 02:26
Duplicate of #613

**Comment by CovertJaguar** [comment] 2015-05-21 02:27
This is a bug on Cauldron's end. It cannot/will not be fixed.

**Closed by CovertJaguar** 2015-05-21 02:26 UTC

**Comment by liach** [comment] 2015-05-21 02:34
Note: Official KCauldron download is [here] (https://prok.pw/git/Prototik/KCauldron/releases).

**Comment by 1337phreak** [comment] 2015-05-21 02:52
Bummer, thanks anyway, and for the official kcauldron link too.
