### ISSUE TITLE
Crash when opening Coke Oven GUI - Illegal Argument Exception - [Cannot create a fluidstack from a null fluid]

### ISSUE THREAD

**Issue by Cooolaid** [CovertJaguar/Railcraft#586] opened 2015-04-18 00:49 UTC
I constructed a Coke Oven and when trying to access its GUI, I get an Immediate crash.
Illegal Argument Exception: Cannot create a fluidstack from a null fluid

I am using (Railcraft_1.7.10-9.5.0.0)
my forge is - v10.13.3.1370

http://pastebin.com/75tqRG0H
.

**Comment by CovertJaguar** [comment] 2015-04-18 01:38
Don't update forge yet.

Duplicate of #581

**Closed by CovertJaguar** 2015-04-18 01:38 UTC
