### ISSUE TITLE
Diesel Locomotive?

### ISSUE THREAD

**Issue by excelcrafter** [CovertJaguar/Railcraft#733] opened 2015-11-23 02:09 UTC
Maybe new locomotive which can use diesel, fuel ( buildcraft ) biodiesel ( immersive engineering )
methanol, ethanol, or some other liquid fuel?

MFE cart is just too heavy to pull with electric loco to use it like mobile battery.

I was thinking about to use tank cart filled with steam as "fuel source" for steam loco, didnt try yet :D but I will try asap, haha

**Comment by Forecaster** [comment] 2015-11-23 08:51
Duplicate of #651

**Closed** 2015-11-24 04:39 UTC
