### ISSUE TITLE
Black Screen on Mac?

### ISSUE THREAD

**Issue by xaleb** [CovertJaguar/Railcraft#552] opened 2015-03-18 23:37 UTC
http://pastebin.com/Jb3NVhFV Here is the log, my friends are having trouble running this collection of mods all together on their macs..and the issue seems to be when railcraft is included. But all Windows and Linux operating system are running them all smoothly and efficiently. They are getting black screens when clicking single or multiplayer, and the game is just hanging up. The only out is to force quit. Suggestions?

**Comment by CovertJaguar** [comment] 2015-03-19 07:53
Duplicate of #553

**Closed by CovertJaguar** 2015-03-19 07:53 UTC
