### ISSUE TITLE
Creosote Duplication Bug

### ISSUE THREAD

**Issue by Givemeyourgits** [CovertJaguar/Railcraft#700] opened 2015-09-29 06:23 UTC
If you put multiple Extra Utilities Drums into a chest that is connected to a Coke Oven (I'm using Item Conduit) and it pulls them all in, it will fill them all simultaneously as if it was one drum but it will result in a stack of filled drums.

**Comment by CovertJaguar** [comment] 2015-09-29 15:50
Duplicate of #625

**Closed by CovertJaguar** 2015-09-29 15:50 UTC
