### ISSUE TITLE
Unloaders with filter do not send carts when set to all and complete.

### ISSUE THREAD

**Issue by jodamm** [CovertJaguar/Railcraft#710] opened 2015-10-12 18:09 UTC
I have set up an unloader with a filter for cobblestone set to all and redstone to complete. When all cobblestone is unloaded from the cart and something else is in the cart, the unloader is not sending the cart until every cobblestone is removed from the buffer and adjacent inventories.

**Comment by CovertJaguar** [comment] 2016-10-05 23:57
Cannot reproduce in 1.10, closing.

**Closed by CovertJaguar** 2016-10-05 23:57 UTC
Labels: bug, needs verification, priority-low
