### ISSUE TITLE
Locking track in holding mode sending carts back

### ISSUE THREAD

**Issue by ajwalters95** [CovertJaguar/Railcraft#673] opened 2015-08-01 14:09 UTC
When a redstone signal is applied it is sending the cart back in the direction it came from instead of boosting it along in the direction it was heading. As far as I can tell this isn't how its supposed to work.

I'm using Railcraft version 9.6.1.0

**Comment by wshadow** [comment] 2015-08-07 11:31
Works fine for me. I just tested with the same version, single chestcart on a flat piece of track. Can you describe your setup? Maybe post a screenshot?

**Comment by ajwalters95** [comment] 2015-08-07 12:31
I'll do you one better. I recorded this and threw it on Youtube.

https://youtu.be/TWooGfy0P7Y

As you see from the video, it works right at the start but then it won't let the cart pass going the other way. This leads me to believe that I am doing something wrong but I can't seem to figure out what.

I am using it in a modpack... Could that be the issue?

**Comment by wshadow** [comment] 2015-08-07 12:45
Oh, I see where the issue is. If you don't deactivate the redstone signal, this happens. So as a quick fix, just make sure to turn off the signal, once the cart is on it's way.

And maybe this will be fixed in a future version.

**Comment by Aleszp** [comment] 2015-08-23 20:04
The same happens to me in 9.7.0.0. This bug prevents from making carts (without locomotive) be controllable like in Forecaster's tutorial about keeping trains apart (as carts without loco won't continue from locking track in locking mode and holding mode is bugged).

**Comment by SamDiego** [comment] 2015-11-29 02:30
I can confirm this very issue with railcraft version 9.8.0.0 in the pack FTB infinity evolved. Makes impossible to automate and signal control separated carts.

**Comment by wshadow** [comment] 2015-11-30 13:05
Regarding the ,,Makes impossible to automate and signal control separated carts'' -> use pulses to send the carts on their way. To do that, you could use a detector right under the holding track (pointing up into the track)

**Comment by SamDiego** [comment] 2015-11-30 18:59
It doesn't matter, the problem is when the cart doesn't need to stop, it goes back like in the video ajwalters95 sent.

**Comment by ajwalters95** [comment] 2015-11-30 19:22
I never found a solution. I had to find another way to automate the system which is a shame because I was trying to focus on using Railcraft.

**Comment by SamDiego** [comment] 2015-11-30 19:28
I had to make a overcomplicated one way loop for 2 carts, thankfully locomotives seems fine to automate.

**Comment by wshadow** [comment] 2015-11-30 21:44
@SamDiego, @ajwalters95 see this: https://youtu.be/9WLMqT5mZPs

**Comment by SamDiego** [comment] 2015-12-01 06:10
Well that works when the cart has permission to go but what if you need to hold it to avoid a collision?  The detector would make it go always..

**Comment by ssotangkur** [comment] 2015-12-02 10:17
I'm really hoping this wasn't introduced w/ my changes.

**Comment by wshadow** [comment] 2015-12-02 13:58
@SamDiego well, use an and gate. Or some other contraption to interrupt the incomming signal between carts. I have another video how this could be done. I'm sure the redstone is terribly bulky and over complicated. Feel free to come up with something better: https://youtu.be/Am4_FjJLH7Y

Also, this is meant as a workaround. Since this is already flagged as bug-major, I expect is to be fixed in one of the next releases.

**Closed** 2016-10-06 00:33 UTC
Labels: bug, priority-medium

**Comment by jooscher** [comment] 2016-11-30 09:40
Hi there everyone!
I just stumbled upon this bug when trying to setup an automated system.
I am playing with Bevo's Modpack atm, which uses Railcraft 9.12.2.0.
Is this bug fixed in more recent versions?

**Comment by CovertJaguar** [comment] 2016-11-30 10:05
Yes, it is fixed in 10.0.0

**Comment by jooscher** [comment] 2016-11-30 10:08
Thanks for the quick response!
Really appreciate your work and support!
