### ISSUE TITLE
Minefactory and Railcraft fighting over steam

### ISSUE THREAD

**Issue by border999** [CovertJaguar/Railcraft#595] opened 2015-04-25 22:00 UTC
I just updated to the latest version of Railcraft and this error appeared during startup.
cpw.mods.fml.common.loaderexception: java.lang.RuntimeException: A mod has attempted to assign BlockID mods.railcraft.common.fluids.BlockRailcraftFluidFinite@71c31c73 to the Fluid 'steam' but this Fluid has already been linked to BlockID powercrystals.minefactoryreloaded.block.fluid.BlockFactoryFluid@643b0c37. Configure your mods to prevent this from happening.
Both Railcraft and MFR are the latest available for noting purposes.
I have tried disabling steam in the railcraft config but it would seem that it hasn't worked.
If the mod author can find a fix or a work around I would be grateful.

**Comment by ipatrol** [comment] 2015-04-26 01:49
Confirmed as reproducible, likewise.

**Comment by CovertJaguar** [comment] 2015-04-26 03:33
Duplicate of #592

**Closed by CovertJaguar** 2015-04-26 03:33 UTC
Labels: duplicate
