### ISSUE TITLE
Duplication Bug in Coke Oven with x500mb Liquid

### ISSUE THREAD

**Issue by xenexelen** [CovertJaguar/Railcraft#597] opened 2015-04-26 07:08 UTC
I put some liquidcontainer (for example Forestry "Wax Capsule") in the Coke Oven.
If the Liquid not exacly a multiple of 1000mb, there are 2 options:

500mb: The containeramount will be nearly duplicate (64 Empty Wax Capsule => 63 Empty in the output)
x500mb: The container will be allways filled...

**Comment by CovertJaguar** [comment] 2015-04-26 07:09
Check the closed issues please...

Duplicate of #593

**Closed** 2015-04-26 07:21 UTC
Labels: duplicate
