### ISSUE TITLE
Glass Bottle dupe with Coke Oven [9.6.0.0]

### ISSUE THREAD

**Issue by SephirothWS** [CovertJaguar/Railcraft#594] opened 2015-04-25 14:04 UTC
It seems this is a thing when there's less than a buckets worth of creosote oil inside the coke oven. I place 2 or more glass bottles in the coke oven's slot for filling bottles and what have you with creosote, and it'll "use" 1 glass bottle and produce two new empty bottles in the results slot. This gives me 3 glass bottles, and I can keep repeating this process for infinite glass bottles. If I put a full stack of glass bottles in the top slot, it'll use one and give me 64 back.

**Comment by Forecaster** [comment] 2015-04-25 14:31
Duplicate of #593

**Closed** 2015-04-25 14:43 UTC

**Comment by SephirothWS** [comment] 2015-04-25 14:45
My apologies. Didn't think to look at the closed reports.
