### ISSUE TITLE
Entire train duped itself

### ISSUE THREAD

**Issue by Deadlock989** [CovertJaguar/Railcraft#762] opened 2016-01-05 23:27 UTC
A steam loco train with one chest cart and one anchor cart just duped itself. Playing in MP, FTP Infinity Evolved pack. Not staff on that server so can't provide any context or logs. Can't reduplicate, seems to have randomly just happened after that train ran for about 12 hours around a circular track. Chest was empty and so was the copy. But the copy of the loco had the same fuel and water, and the copy of the anchor had the same time and same number of ender pearls in the slot.

**Comment by liach** [comment] 2016-01-06 00:08
Ask the moderator for the log and the world.

**Comment by Forecaster** [comment] 2016-01-06 00:34
This had been known to happen before. Pretty sure it's a vanilla issue.

**Comment by EntropicPariah** [comment] 2016-01-09 09:08
It happened to me already. I think it's a chunkloading issue because my machine is slow. I get stuttering at high speed so it's like the chunk unloaded without registering that the train had moved so when I came back later there was a duplicate train. Chest had all the same stuff in it too.

**Comment by beringtom** [comment] 2016-01-13 16:18
Can confirm this, usually only happens after server restarts.

**Comment by beringtom** [comment] 2016-01-21 22:53
Anyone found any reason to this? is it a chunkloading issue?

**Comment by beringtom** [comment] 2016-01-26 23:14
okay so I tried to do some digging, this is happening on our 1.7.10 server, with 9.8.0.0 and Forge 10.13.4.1492 and ONLY  the trains that are running would be duped, (sometimes 3 times).

Can @Deadlock989 and @EntropicPariah share their setup details?

**Comment by CovertJaguar** [comment] 2016-03-07 07:23
This is a long standing bug in Vanilla that is far beyond my ability to fix. You'll need to bug Mojang.

Also this is a duplicate of #613

**Closed by CovertJaguar** 2016-03-07 07:23 UTC
