### ISSUE TITLE
Railcraft and Minefactory Reloaded fighting over Fluid "Steam"

### ISSUE THREAD

**Issue by AgentJava** [CovertJaguar/Railcraft#596] opened 2015-04-26 01:47 UTC
In the new version of Railcraft (9.6.0.0), everything works fine until MFR is installed. It crashes the game when MFR is installed. And I already tested that if I get rid of Railcraft, MFR works and nothing crashes. But, I can't live without Railcraft, so please help me.

Summary of the Crash Log:
A mod has attempted to assign BlockID mods.railcraft.common.fluids.BlockRailcraftFluidFinite@7051e679 to the Fluid 'steam' but this Fluid has already been linked to BlockID powercrystals.minefactoryreloaded.block.fluid.BlockFactoryFluid@79eb7803. Configure your mods to prevent this from happening.

**Comment by CovertJaguar** [comment] 2015-04-26 03:34
Duplicate of #592

**Closed by CovertJaguar** 2015-04-26 03:34 UTC
